const cardInfo = [
  {name:"Col. Mustard",img:"art/mustard.png",color:"yellow"},
  {name:"Prof. Plum",img:"art/plum.png",color:"purple"},
  {name:"Mr. Green",img:"art/green.png",color:"green"},
  {name:"Ms. Peacock",img:"art/peacock.png",color:"blue"},
  {name:"Miss Scarlet",img:"art/scarlet.png",color:"red"},
  {name:"Mrs. White",img:"art/white.png",color:"white"},
  {name:"Knife",img:"art/knife.png",color:"grey"},
  {name:"Candlestick",img:"art/candlestick.png",color:"grey"},
  {name:"Revolver",img:"art/revolver.png",color:"grey"},
  {name:"Rope",img:"art/rope.png",color:"grey"},
  {name:"Lead Pipe",img:"art/pipe.png",color:"grey"},
  {name:"Wrench",img:"art/wrench.png",color:"grey"},
  {name:"Hall",img:"art/hall.png",color:"lightgrey"},
  {name:"Lounge",img:"art/lounge.png",color:"lightgrey"},
  {name:"Dining Room",img:"art/diningroom.png",color:"lightgrey"},
  {name:"Kitchen",img:"art/kitchen.png",color:"lightgrey"},
  {name:"Ballroom",img:"art/ballroom.png",color:"lightgrey"},
  {name:"Conservatory",img:"art/conservatory.png",color:"lightgrey"},
  {name:"Billiards Room",img:"art/billiardsroom.png",color:"lightgrey"},
  {name:"Library",img:"art/library.png",color:"lightgrey"},
  {name:"Study",img:"art/study.png",color:"lightgrey"}
];
